### ISSUE TITLE
Data Verifier

### ISSUE THREAD

**Issue by konvoulgaris** [DIASTEMA-UPRC/data-verifier#1]
A service that verifies if data is valid for analysis

Response:
```
{
  “minio-input” : “bucket/to/folder”
}
```

Result
```
{
  “result”: “valid” | “invalid” | “suggested”
  “reason”: <string_reason>
}
```

**Comment by konvoulgaris** [comment]
Service implemented. @karamolegkos please do integration testing and such with the following docker image:
`konvoulgaris/diastema-data-verifier:latest`

Make sure to check the [README](https://github.com/DIASTEMA-UPRC/data-verifier/blob/main/README.md) for any environment variables you need to set.

**Comment by karamolegkos** [comment]
This service is working and has successfully passed the integration phase ✔️.
After the next Internal Meeting, I propose we move it as Done @yannispoulakis .
