### ISSUE TITLE
Data Ingestion Accepted Formats

### ISSUE THREAD

**Issue by yannispoulakis** [DIASTEMA-UPRC/data-verifier#4]
Data Ingestion should not accept http responses that cannot be transformed to a valid dataset.

**Comment by adreaskar** [comment]
Αυτό θα γίνεται αυτόματα πλέων στο Ingestion Service, έπειτα απο τις αλλαγές που θα γίνουν για τα άλλα issues.

Basically αν ένα request δεν είναι valid dataset θα επιστρέφεται μήνυμα λάθους.

Please confirm @konvoulgaris  @karamolegkos

**Comment by karamolegkos** [comment]
I confirm!
